cpp/src/core/library.cpp, python/legate_dataframe/lib/core/scalar.pyx
I'm slowly working on replacing cudf's `DeviceScalar` with pylibcudf's `Scalar` eventually. The first step is slimming down the old API so replacing `as_device_scalar` with an equivalent `cudf.Scalar.device_value` (which _should_ be API stable)
=> Replace as_device_scalar with cudf.Scalar.device_value

.dockerignore, Dockerfile, ci/manual-ci-test.py, ci/run_pytests.sh, cpp/src/core/library.cpp, cpp/src/core/repartition_by_hash.cu, cpp/tests/test_cudf_interop.cpp, cpp/tests/test_repartition_by_hash.cpp, cpp/tests/test_task.cpp
This is just Wonchan's old PR with small comments added.  I plan to open an issue about actually adding at least some estimates about memory usage. This may not matter for many simple pipelines, but also could matter a lot for some.
(Memory use is not easy to bound, e.g. for joins or csv reading, although even a very high overestimate may be useful if we read a small csv for example.)
=> MAINT: Quick fix for the one pool world

cpp/src/core/library.cpp, python/tests/test_csv.py
Each column takes up some space in the return and this space is currently limited but settable.
This bumps the limit for all tasks so that we should be able to use well above 100 columns everywhere.
(Clearly, it is very plausible that we might bump this further if we run into a use-case that needs that.)
---
Tested just with csv, since that is where it came up (but if used, it tends to be the first call).  Either way, it should affect everything, so set it globally.
=> ENH: Support more return columns

cpp/include/legate_dataframe/core/library.hpp, cpp/include/legate_dataframe/stream_compaction.hpp, cpp/src/core/library.cpp, cpp/src/stream_compaction.cpp, cpp/tests/test_stream_compaction.cpp, docs/source/api/table_funcs.rst, python/legate_dataframe/lib/CMakeLists.txt, python/legate_dataframe/lib/stream_compacation.pyi, python/legate_dataframe/lib/stream_compaction.pyx, python/tests/test_csv.py, python/tests/test_stream_compaction.py, python/tests/test_tasks.py
Adding it with a similar file structure to libcudf which uses
``stream_compaction``.  (Not sure about the names, but also good to
keep aligned with libcudf.)
Straight forward exposure of the table-wise boolean masking.
---
Other fixup is due to sorting tests running into issues with the high column things now, so lowered it.
(It must be unrelated, but the `test_task.py` seemed to hang when run as an individual test.)
=> ENH: Add ``apply_boolean_mask``

conda/recipes/legate-dataframe/conda_build_config.yaml, cpp/src/core/repartition_by_hash.cu, cpp/src/groupby_aggregation.cpp, cpp/src/join.cpp, cpp/src/sort.cpp, python/tests/test_sort.py
The local chunks may be empty and the sort code must make sure to deal with it:
* An empty local table cannot share split points (the way it is done here)
* As no split points are shared, the total number of split points may be fewer than the number of ranks.
We need to deal with both of these.  Now that there is boolean masking it can be used to trigger these paths reliably (currently at least).
=> BUG: Sort code must deal with zero row local chunks

conda/recipes/legate-dataframe/meta.yaml
I am not sure if this should also be included in the dependencies.yaml, but I suppose it shouldn't matter too much there for a release at least. (conda didn't seem to like just adding it?)
This is identical to legate-boost (which needs to pick cpu or gpu depending on the build).
=> BLD: Ensure we fetch the `_gpu` tag version

conda/recipes/legate-dataframe/meta.yaml
Run-exports is only picked up from the current build step (which makes sense, since they can differ), but this means that we need to manually include anything that we want to pick up in the host/build section (i.e. mostly legate).
Since cudf/rmm already depend on pylibcudf, libcudf, and librmm, I have not duplicated these.
**Do not merge until version upload is clarified.**
=> BLD: Fix split recipe dependencies [skip ci]

conda/environments/all_cuda-124_arch-x86_64.yaml, cpp/include/legate_dataframe/csv.hpp, cpp/src/csv.cpp, dependencies.yaml, python/legate_dataframe/lib/csv.pyi, python/legate_dataframe/lib/csv.pyx, python/tests/test_csv.py
We still don't allow usecols just being indices (we could).
In general, I would like to move to use csv_options at some point (even if we have to copy out the ones we can deal with), but that might take a bit and it seemed that this is a bit of a pain point.
TBH, I am a bit confused about the need for sorting, but it seems I also was confused about it previously (i.e. further down there is another sort).
=> ENH: Support `names=` in csv reading to not provide a header

conda/environments/all_cuda-124_arch-x86_64.yaml, dependencies.yaml
A pin like `sphinx!=8.2.0` was added in #30, I'm guessing for similar reasons as documented in  https://github.com/rapidsai/build-planning/issues/155.
That can't be removed until some upstream changes are made in `nbsphinx` (linked in that issue). This proposes changing the pin to `<8.2.0` (to prevent CI breaking again if an 8.2.1 or 8.3.0 is released) and adding a comment explaining when it can be removed.
=> require sphinx<8.2.0

.github/workflows/conda-python-build.yaml, .pre-commit-config.yaml, ci/build_all.sh
Similar to https://github.com/rapidsai/legate-raft/pull/15
Enables `sccache` in builds, to hopefully save some CI time, memory, and compute.
Since I'm touching the repo anyway, also updates the RAPIDS-specific `pre-commit` hooks to their latest versions.
=> enable sccache in builds, update some pre-commit hooks

cpp/include/legate_dataframe/core/column.hpp, cpp/include/legate_dataframe/core/table.hpp, cpp/src/core/column.cu, cpp/src/core/table.cpp, cpp/src/join.cpp, cpp/tests/test_task.cpp, python/tests/test_csv.py, python/tests/test_join.py, python/tests/test_sort.py
This is breaking as we stop passing around `global_num_rows`, but this
should improve legate's ability to parallelize task launches (I think)
since fetching the `global_num_rows` on an unbound table requires blocking.
`is_partitioned` should also be a safer API here, because the local and
global number of rows could be equal if all but one chunks have 0 entries
(which is may be hard to trigger but is possible with filtering).
---
* I removed `global_num_rows` for now.  It may well be useful again eventually.
* The test did hang without the fix, but not 100% sure if that was actually the bug I expected :).
=> API,BUG: Remove `global_num_rows`, use `is_partitioned`

ci/build_all.sh
These are now equivalent in behavior. However support for `conda-mambabuild` is being dropped. So switch to `conda-build`.
xref: https://github.com/rapidsai/build-planning/issues/149
=> Replace `conda-mambabuild`with `conda-build`

cpp/include/legate_dataframe/core/library.hpp, cpp/include/legate_dataframe/reduction.hpp, cpp/src/reduction.cpp, cpp/src/utils.cpp, cpp/tests/test_reduction.cpp, docs/source/api/column_funcs.rst, python/legate_dataframe/lib/CMakeLists.txt, python/legate_dataframe/lib/core/column.pyx, python/legate_dataframe/lib/reduction.pyx, python/tests/test_reduction.py
This implements basic aggregations using a similar pattern to the simple aggs/finalizer used in parts of cudf.
Since that pattern doesn't take into account the initial value and is in the `detail` API, opted instead to create a custom helper.
That is, we use `(dtype, agg, initial)` to identify each reduce and then split the reduce into two steps:
1. A first-pass that reduces only locally.
2. A finalize pass that works with local results or other final
results.
Supporting further aggregations should be straight forward additions in the future.
The design should generalize relatively well to re-use for other aggregations (e.g. maybe to improve groupby-aggs) or to calculate multipe aggregations for the same column (since e.g. many need the sum or count temporary result).
The one thing that …
=> ENH: Implement basic reductions

cpp/tests/test_csv.cpp, cpp/tests/test_parquet.cpp
This was probably useful in debugging at some point, but survived and got cargo-culted.  I noticed that the tmp folder gets filled up a lot (I think to the point of tests not passing).
=> TST: Clean up temporary cpp test directories

ci/build_docs.sh, ci/run_ctests.sh, ci/run_pytests.sh, cpp/CMakeLists.txt, cpp/include/legate_dataframe/core/transposed_copy.cuh, cpp/include/legate_dataframe/parquet.hpp, cpp/src/core/transposed_copy.cu, cpp/src/parquet.cpp, docs/source/api/io.rst, python/legate_dataframe/lib/core/legate.pxd, python/legate_dataframe/lib/parquet.pyi, python/legate_dataframe/lib/parquet.pyx, python/tests/test_parquet.py, python/tests/test_tasks.py
This adds a call to do a chunked copy directly into a transposed array. To be honest, the only reason to do this inside legate-df, is that we have the cudf dependency here anyway.
To some degree, the reason is just to work-around current legate issues with too many columns.
---
Always trickier then I expect... @RAMitchell this should allow reading in these huge tables, effectively directly to cupynumeric via `nullable=False` and then just using `cupynumeric.asarray()`.
I am not sure if the chunking choice here is ideal, i.e. whether this is as faster as it can be.  The tranpose-copy is very similar to the "interleaved copy" in cudf, and I can imagine that it could be sped up as well.
=> API: Allow parquet reading into (transposed) array

README.md, cpp/include/legate_dataframe/core/library.hpp, cpp/include/legate_dataframe/unaryop.hpp, cpp/src/unaryop.cpp, cpp/tests/test_unaryop.cpp, docs/source/api/column_funcs.rst, python/legate_dataframe/lib/unaryop.pyi, python/legate_dataframe/lib/unaryop.pyx, python/tests/test_tasks.py, python/tests/test_unaryop.py
Add API to allow casting a single column (for now functional).
=> API: Add `unaryop.cast` to cast a single column

.pre-commit-config.yaml, build.sh, scripts/run-cmake-format.sh
Contributes to https://github.com/rapidsai/build-planning/issues/135
Adds `shellcheck` to `pre-commit`, to catch issues like unsafe access patterns, unused variables, etc. in shell scripts.
Fixes these warnings:
```text
SC2046 (warning): Quote this to prevent word splitting.
SC2068 (error): Double quote array expansions to avoid re-splitting elements
```
=> add shellcheck to pre-commit

cpp/CMakeLists.txt, cpp/include/legate_dataframe/utils.hpp, cpp/src/parquet.cpp, cpp/src/utils.cpp
This uses arrows parquet reader to read the metadata from the file.  This will need
a little bit of polishing for odder data types
A wrinkle is that the dtype conversion is certainly not complete (and also note tested for all types here).
Should address the hopefully larger issue in gh-47, it will still decompress too much data and use a larger memory overhead with large row group chunk sizes.
(Not sure the CI will build, I think we effectively pull in arrow via cudf, but we should have it as an explicit dependency with gh-53.)
=> Use arrow to read parquet metadata

cpp/src/core/column.cu
Since it is currently called from outside tasks, this lingering bug probably has no effect (the offset is always 0).
But this was a useful pattern when allowing eager allocations more generally and writing output in gh-57 where this then triggers.
So let's just fix it, even if it may not ever be hit without gh-57.
=> BUG: Fix offset for and add sanity check to maybe_bind_buffer

cpp/src/parquet.cpp
The old value didn't make sense, this should be in bytes. (I doubt this makes a difference, since the old value should just have been too small.)
https://docs.rapids.ai/api/libcudf/stable/classcudf_1_1io_1_1chunked__parquet__reader#a49f5549b53257828d50f5fa65114e07a
=> Fixup parquet chunking

cpp/src/core/library.cpp, cpp/src/csv.cpp, cpp/src/groupby_aggregation.cpp, cpp/src/join.cpp, cpp/src/parquet.cpp, cpp/src/sort.cpp
Based on guidance from the legate team, add the `with_elide_device_ctx_sync` to indicate to realm that we are using the task stream. This should still guarantee correct sychronization for output tasks because sychronization still happens, we just indicate that we do use the task stream and thus synching that is sufficient.
We also should indicate that the output csv/parquet writer tasks have side effects.  In practice, I don't think we hit any problems due to it, but it is just correct (e.g. gh-64 is unrelated).
Closes gh-66
=> MAINT,BUG: Indicate that we are using the task stream and side-effect

ci/run_pytests_cpu.sh, cpp/include/legate_dataframe/core/ranges.hpp, cpp/include/legate_dataframe/utils.hpp, cpp/src/core/column.cu, cpp/src/core/ranges.cu, cpp/src/utils.cpp, python/tests/test_arrow.py
Does not yet use them when our strings are larger than 2GiB. I need this for polars interop because polars tends to create large strings (probably just always).
(So tested there, but not here, but I guess we could add explicit arrow round-trip tests.)
Basically, just duplicating.  Templating didn't seem much better considering how short the snippets were, but if you have an idea, happy to change.
=> ENH: Allow ingesting arrow large strings and fix timedelta/datetime roundtrip

README.md, cpp/examples/hello.cpp, cpp/include/legate_dataframe/csv.hpp, cpp/include/legate_dataframe/parquet.hpp, cpp/src/csv.cpp, cpp/src/parquet.cpp, cpp/tests/test_csv.cpp, cpp/tests/test_parquet.cpp, python/examples/hello_world.py, python/legate_dataframe/ldf_polars/dsl/ir.py, python/legate_dataframe/lib/csv.pyi, python/legate_dataframe/lib/csv.pyx, python/legate_dataframe/lib/parquet.pyi, python/legate_dataframe/lib/parquet.pyx, python/tests/test_csv.py, python/tests/test_parquet.py
This may make the C++ API somewhat inconvenient here, so I would be happy to introduce an overload for a single string that uses glob (potentially moving it back from Python to C++).
OTOH, I feel a bit that glob utility is maybe enough in C++ (and I am not sure we should care too much about convenience there)
While multiple files are usually globs, polars will helpfull expand them so that we need this version.
Breaks:
* C++ API for file loading.
* Python API if you pass the path as keyword arg (which seems niche)
=> API: Allow iterable of files and move globbing to Python for readers

cpp/src/binaryop.cpp, cpp/src/parquet.cpp, cpp/src/replace.cpp, cpp/src/unaryop.cpp
Legate has some issues around image constraints, which means we have to very explicitly set them for all involved variables (most annoyingly the mask, I didn't check if that may be enough).
With that, the constraints work though.  This also fixes some CPU paths.
This is a follow-up to gh-57, because I didn't want that to bloat even more with such hacks (in the end, the hack isn't too bad, though).
---
The rects were set up for the array case, but not actually used (because 2-D is still broken anyway).  But really, legate should probably support the 1-D setup also for the 2-D case.
Test locally with multiple GPUs with a number where the image constraint matters.
=> Also add support for parquet and eager alloc flag (and fix CPU paths)

python/legate_dataframe/lib/core/table.pyx, python/tests/test_table.py
We need to use the `to_array()` function to work around the nullability issue and add the convenience of allowing epxort when there are no nulls (by doing an actual count if needed).
The initial/old version was missing this.
---
Admittedly, the test isn't _quite_ spot-on, because I think the conversion from arrow will make the column non-nullable (seeing there are no nulls).  So only the second part really tests things (by checking for the custom error that comes from counting).
=> BUG: `LogicalTable.to_array()` should use the column `to_array()`

python/legate_dataframe/ldf_polars/containers/column.py, python/legate_dataframe/ldf_polars/containers/dataframe.py, python/legate_dataframe/ldf_polars/dsl/ir.py, python/tests/test_table.py
In most cases, these are actually pushed to a lower level and would be better tested on the individual function, but the test does catch at least one of the table paths.
In practice, e.g. sorting also should get the `limit=` so that the distributed sort can do less work (even if it still will do/need the final slice).
=> Finish support for slice/head/tail in polars

cpp/src/sort.cpp, python/tests/test_sort.py
All except the stable GPU sort code paths seems to just forgive the same column being repeated multiple times, but this one crashed pretty cryptically (and the old tests accidentally triggered that).
I have not thought about dropping the key (although you would have to also drop the second order if passed)
=> Fix multi-gpu sort tests and tighten duplicate column check

cpp/include/legate_dataframe/sort.hpp, cpp/src/sort.cpp, python/legate_dataframe/ldf_polars/dsl/ir.py, python/legate_dataframe/lib/sort.pyi, python/legate_dataframe/lib/sort.pyx, python/tests/test_sort.py
Adds `limit=` to sorting, since at least until we have `top/bottom_k` like functionality, a head/tail call lowered into sorting means a much easier task for a distributed sort.
(once we have `top_k` via [libcudf](https://github.com/rapidsai/cudf/issues/19096), I am not certain that there would be much of a niche left for this.)
=> Implement limit to sorting

conda/environments/all_cuda-124_arch-x86_64.yaml, conda/recipes/legate-dataframe/conda_build_config.yaml, conda/recipes/legate-dataframe/meta.yaml, cpp/CMakeLists.txt, dependencies.yaml
This is largely cargo-culted from raft.  It seems that newer legate versions do not use nccl anymore and our transitive dependency will break.
Not clearly tested without the new legate, so we may want to wait until we actually see the change (which means until cupynumeric updates it's legate dependency).
---
Ping @reazulhoque since you ran into this with the newer legate.
=> Add explicit NCCL depdencency

cpp/include/legate_dataframe/core/library.hpp, cpp/src/binaryop.cpp, cpp/src/csv.cpp, cpp/src/filling.cpp, cpp/src/groupby_aggregation.cpp, cpp/src/join.cpp, cpp/src/parquet.cpp, cpp/src/reduction.cpp, cpp/src/replace.cpp, cpp/src/sort.cpp, cpp/src/stream_compaction.cpp, cpp/src/timestamps.cpp, cpp/src/unaryop.cpp
Intermittently, legate didn't support this pattern, so we had to add the TASK_CONFIG init to every task and change the registration pattern to happen late (rather than at any time).
This was only necessary temporarily, but I had not reverted it before.
=> MAINT: Revert task registration restructure

cpp/include/legate_dataframe/core/library.hpp, cpp/src/join.cpp
If we don't need a communicator because we have a broadcast join, we also don't need a concurrent task launch at all.
Includes gh-95 to make the templating slightly nicer.
---
Didn't try locally (machine I usually use is currently unavailable).
=> ENH: Inform legate that some joins don't need a concurrent task launch

cpp/include/legate_dataframe/binaryop.hpp, cpp/include/legate_dataframe/core/column.hpp, cpp/include/legate_dataframe/csv.hpp, cpp/src/binaryop.cpp, cpp/src/binaryop.cu, cpp/src/csv.cpp, cpp/src/csv.cu, cpp/src/reduction.cpp, cpp/tests/test_binaryop.cpp, cpp/tests/test_csv.cpp, python/legate_dataframe/lib/binaryop.pyx, python/legate_dataframe/lib/core/data_type.pxd, python/legate_dataframe/lib/core/data_type.pyx, python/legate_dataframe/lib/csv.pyx
Start with binaryop and readcsv. Split into .cu and .cpp files to prepare for cpu only compilation. Also change cudf data types to arrow data types in function signature.
=> Refactor cuda code into .cu files

cpp/src/binaryop.cu, cpp/src/parquet.cpp, python/legate_dataframe/ldf_polars/__init__.py, python/legate_dataframe/ldf_polars/dsl/expr.py, python/legate_dataframe/ldf_polars/dsl/expressions/binaryop.py, python/legate_dataframe/ldf_polars/dsl/expressions/datetime.py, python/legate_dataframe/ldf_polars/dsl/translate.py, python/legate_dataframe/ldf_polars/utils/dtypes.py, python/legate_dataframe/lib/timestamps.pyx, python/tests/test_binaryop.py, python/tests/test_table.py, python/tests/test_timestamps.py
We should still expose datetime component extraction for CPU as well probably, that might change things, but hopefully too annoyingly so.
I think true-divide (at least for polars) is main useful thing, while divide I believe is a floor-divide, which we could expose but only easily for non-floats probably.
So, hacked true-divide to work, although one day we may want to lower that.
=> Expose datetime component to polars and fix true-divide

cpp/include/legate_dataframe/copying.hpp, cpp/include/legate_dataframe/core/library.hpp, cpp/src/copying.cpp, cpp/src/copying.cu, cpp/tests/test_copying.cpp, docs/source/api/column_funcs.rst, python/legate_dataframe/ldf_polars/dsl/expr.py, python/legate_dataframe/ldf_polars/dsl/expressions/ternary.py, python/legate_dataframe/ldf_polars/dsl/translate.py, python/legate_dataframe/lib/CMakeLists.txt, python/legate_dataframe/lib/binaryop.pyx, python/legate_dataframe/lib/copying.pyi, python/legate_dataframe/lib/copying.pyx, python/tests/test_copying.py, python/tests/test_tasks.py
This adds the ternary copy_if_else operation functionality. I put it into `copying.cpp`, etc. since most of our structure matches libcudf right now (and that's where it is there).
=> Expose `copying.copy_if_else` and corresponding polars API

cpp/include/legate_dataframe/join.hpp, cpp/src/join.cpp, cpp/src/join.cu, cpp/tests/test_join.cpp, python/legate_dataframe/ldf_polars/dsl/ir.py, python/legate_dataframe/lib/join.pyi, python/legate_dataframe/lib/join.pyx, python/tests/test_join.py
These are slightly different, mainly since the rhs is just used for filtering so they never return columns.  Otherwise they are straight forward, though.
(Conditional joins support for polars is trickier, we could probably create a basic working version easily via pre-processing but lowering conditional logic to both libcudf and arrow could get annoying.)
=> ENH: Add semi and anti joins

python/legate_dataframe/ldf_polars/containers/column.py, python/legate_dataframe/ldf_polars/dsl/expressions/unary.py, python/tests/test_groupby_aggregation.py
This should be a bit nicer and it could be soon, but I also doubt that it is speed relevant.
(I.e. the nice thing would be to just create a new mask, but that requires the ability to create a new array that uses the old store easily which should be in legate pretty soon though.)
=> Enable polars groupby min/max by adding minimal mask_nans functionality
